[package]
name = "mn"
version = "0.1.0"
authors = ["Eirik Brandtzæg <eirikb@eirikb.no>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11.7", features = ["json"] }
tokio = { version = "1.15.0", features = ["full"] }
clap = "2.34.0"