[package]
name = "mn"
version = "0.1.0"
authors = ["Eirik Brandtzæg <eirikb@eirikb.no>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11.10", features = ["json"], features = ["rustls-tls"] }
tokio = { version = "1.17.0", features = ["full"] }
clap = "3.1.6"
