on:
  workflow_dispatch:
  push:

# Plan (tiers):
# A: Build stage4 (for each target)
# B: Hash (create hash for each target)
# C: Build stage3 (for each target)
# D: Build gg
# E Test (for each os target)
# F: Create release

name: gg.cmd
jobs:

  A-stage4-OS:
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            stage42/target
          key: cache1-OS-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: cargo pls
        shell: bash
        run: |
          mkdir -p stage42
          mv stage4/* stage42
          rm -rf stage4
          cd stage42
          
          rustup target add ${{ matrix.target }}
          cargo build --release --target=${{ matrix.target }}
          find . -type f -name stage4.exe -exec cp {} ../stage4 \;
          find . -type f -name stage4 -exec cp {} ../stage4 \;


      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: stage4_${{ matrix.target }}
          path: stage4


  A-stage4-container:
    strategy:
      matrix:
        include:
          - container: alpine
            target: x86_64-unknown-linux-musl

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            stage42/target
          key: cache1-container-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: cargo pls
        run: |
          mkdir -p stage42
          mv stage4/* stage42
          rm -rf stage4
          cd stage42
          if [ "${{ matrix.container }}" == "alpine" ]
          then
            apk add build-base 
            apk add rustup
            rustup-init -y
            source $HOME/.cargo/env
          fi

          cargo build --release --target=${{ matrix.target }}
          #--target=${{ matrix.target}}
          find . -type f -name stage4.exe -exec cp {} ../stage4 \;
          find . -type f -name stage4 -exec cp {} ../stage4 \;


      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: stage4_${{ matrix.target }}
          path: stage4


  A-stage4-arch:
    strategy:
      matrix:
        include:
          - arch: armv7
            target: armv7-unknown-linux-gnu
          - arch: armv7
            target: armv7-unknown-linux-musl

    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.1.0

      - uses: actions/cache@v2
        with:
          path: cachus
          key: cache1-arch-cargo-x7-${{ hashFiles('**/Cargo.lock') }}

      - uses: uraimo/run-on-arch-action@v2
        if: github.ref == 'refs/heads/main'
        name: Run commands
        id: runcmd
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu18.04
          githubToken: ${{ github.token }}
          setup: mkdir -p "$PWD/artifacts"
          dockerRunArgs: |
            -v "$PWD/artifacts:/artifacts"
            -v "$PWD/cachus:/cachus"

          install: |
            apt-get -y update
            apt-get -y install cargo

          run: |
            cd stage4
            cp -rp /cachus/* . || :
            CARGO_HOME=ok cargo build --release
            cp -rp target /cachus/
            cp -rp ok /cachus/
            cp target/release/stage4 /artifacts/

      - if: github.ref == 'refs/heads/main'
        run: |
          sudo chown -R $(id -u):$(id -g) $PWD/artifacts
          sudo chown -R $(id -u):$(id -g) .
          rm -rf stage4
          find $PWD/artifacts -type f -name stage4 -exec cp {} ./stage4 \;

      - if: github.ref == 'refs/heads/main'
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: stage4_${{ matrix.target }}
          path: stage4


  B-hash:
    needs: [ A-stage4-OS, A-stage4-container, A-stage4-arch ]
    runs-on: ubuntu-20.04
    steps:
      - name: Download stage4 hash
        uses: actions/download-artifact@v2

      - name: Rename to hash
        shell: bash
        run: |
          mkdir hash
          mkdir out
          for dir in stage4_*
          do
            file=$dir/stage4
            hash=$(sha512sum $file | awk '{ print $1 }')
            cp $file out/$hash
            echo $hash > hash/hash_$dir
          done

      - name: Upload hash artifact
        uses: actions/upload-artifact@v2
        with:
          name: hash
          path: hash

      - uses: LanceMcCarthy/Action-AzureBlobUpload@v1.9.0
        with:
          connection_string: ${{ secrets.ConnectionString }}
          container_name: $web
          source_folder: out


  C-stage3-OS:
    needs: B-hash

    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Download stage4 hash
        uses: actions/download-artifact@v2
        with:
          name: hash
          path: hash

      - name: Hash
        # ENV -> CMAKE -> Code very hard. This very easy
        shell: bash
        run: |
          hash=$(cat hash/hash_stage4_${{ matrix.target }})
          echo "now hash is $hash"
          echo "const char *hash = \"$hash\";" > stage3/const.h

      - name: Makus
        shell: bash
        run: |
          cd stage3
          if [ "${{ matrix.target }}" == "x86_64-unknown-linux-musl" ]
          then
            sudo apt install musl-dev musl-tools
            export CC=musl-gcc
          fi
          cmake -B build -DCMAKE_EXE_LINKER_FLAGS='-Os' -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          find . -type f \( -name stage3 -o -name stage3.exe \) -exec cp {} ../stage3_${{ matrix.target }} \;
          strip ../stage3_${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: stage3_${{ matrix.target }}
          path: stage3_${{ matrix.target }}


  C-stage3-container:
    needs: B-hash

    strategy:
      matrix:
        include:
          - container: alpine
            target: x86_64-unknown-linux-musl

    runs-on: ubuntu-20.04
    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v2

      - name: Download stage4 hash
        uses: actions/download-artifact@v2
        with:
          name: hash
          path: hash

      - name: Hash
        # ENV -> CMAKE -> Code very hard. This very easy
        run: |
          hash=$(cat hash/hash_stage4_${{ matrix.target }})
          echo "now hash is $hash"
          echo "const char *hash = \"$hash\";" > stage3/const.h

      - name: Makus
        run: |
          cd stage3
          apk add build-base cmake
          cmake -B build -DCMAKE_EXE_LINKER_FLAGS='-Os' -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          find . -type f \( -name stage3 -o -name stage3.exe \) -exec cp {} ../stage3_${{ matrix.target }} \;
          strip ../stage3_${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: stage3_${{ matrix.target }}
          path: stage3_${{ matrix.target }}


  C-stage3-arch:
    needs: B-hash

    strategy:
      matrix:
        include:
          - arch: armv7
            target: armv7-unknown-linux-gnu
          - arch: armv7
            target: armv7-unknown-linux-musl

    runs-on: ubuntu-20.04

    steps:
      - if: github.ref == 'refs/heads/main'
        uses: actions/checkout@v2

      - if: github.ref == 'refs/heads/main'
        name: Download stage4 hash
        uses: actions/download-artifact@v2
        with:
          name: hash
          path: hash

      - if: github.ref == 'refs/heads/main'
        uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu18.04
          githubToken: ${{ github.token }}
          setup: mkdir -p "$PWD/artifacts"
          dockerRunArgs: |
            -v "$PWD/artifacts:/artifacts"
            -v "$PWD:/yes"

          install: |
            apt-get -y update
            apt-get -y install cmake build-essential musl-dev musl-tools

          run: |
            set -x
            cd /yes
            hash=$(cat hash/hash_stage4_${{ matrix.target }})
            echo "now hash is $hash"
            echo "const char *hash = \"$hash\";" > stage3/const.h
            cd stage3
            if [ "${{ matrix.target }}" == "armv7-unknown-linux-musl" ]
            then
              export CC=musl-gcc
            fi
            mkdir build
            cd build
            cmake .. -DCMAKE_EXE_LINKER_FLAGS='-Os' -DCMAKE_BUILD_TYPE=Release
            make
            find . -type f \( -name stage3 -o -name stage3.exe \) -exec cp {} /artifacts/stage3_${{ matrix.target }} \;
            strip /artifacts/stage3_${{ matrix.target }}

      - if: github.ref == 'refs/heads/main'
        run: |
          cp artifacts/* ./

      - if: github.ref == 'refs/heads/main'
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: stage3_${{ matrix.target }}
          path: stage3_${{ matrix.target }}



  D-stage1:
    needs: [ C-stage3-OS, C-stage3-container, C-stage3-arch ]
    runs-on: ubuntu-latest
    steps:
      - name: Source
        uses: actions/checkout@v2.1.0

      - name: Download stage3 / stage4
        uses: actions/download-artifact@v2

      - name: gg.cmd
        run: |
          sudo apt-get install dos2unix
          mv stage1 _stage1
          mv stage2 _stage2
          mv stage3 _stage3
          rm -rf .cache/gg
          mkdir -p .cache/gg
          rm -rf stage1
          for dir in stage3*; do
            echo "dir is $dir"
            for file in "$dir"/*; do
              echo "file is $file"
              cp "$file" .cache/gg/
            done
          done
          # Prevent wine from trying to run (if installed on users PC)
          mv .cache/gg/stage3_x86_64-pc-windows-msvc .cache/gg/stage3_zz_x86_64-pc-windows-msvc
          cp _stage2/stage2.sh .cache/gg/
          cp _stage2/stage2.ps1 .cache/gg/
          chmod +x .cache/gg/stage2.sh
          tar -zpvcf gg.tgz .cache
          unix2dos _stage1/stage1.bat
          cat _stage1/stage1.bat _stage1/stage1.sh gg.tgz > gg.cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: gg.cmd
          path: gg.cmd


  E-test-OS:
    needs: D-stage1
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, windows-2019, windows-2022, macOS-11, macOS-12 ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Download gg
        uses: actions/download-artifact@v2
        with:
          name: gg.cmd

      - name: Run!
        run: |
          file gg.cmd
          head gg.cmd
          sh gg.cmd node -e 'console.log(1)'
          echo "Nice, let's try again"
          sh gg.cmd node -e 'console.log(1)'
          sh gg.cmd node -v
          sh gg.cmd npm -v
          sh gg.cmd npx -v
          sh gg.cmd java -version
          sh gg.cmd java -version

  E-test-batch:
    needs: D-stage1
    strategy:
      matrix:
        os: [ windows-2019, windows-2022 ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Download gg
        uses: actions/download-artifact@v2
        with:
          name: gg.cmd

      - name: Run!
        shell: cmd
        run: |
          .\gg.cmd node -e 'console.log(1)'
          .\gg.cmd node -e 'console.log(1)'
          .\gg.cmd node -v
          .\gg.cmd npm -v
          .\gg.cmd npx -v
          .\gg.cmd java -version
          .\gg.cmd java -version


  E-test-container:
    needs: D-stage1
    strategy:
      matrix:
        container: [ ubuntu, debian, alpine, archlinux ]

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - name: Download gg
        uses: actions/download-artifact@v2
        with:
          name: gg.cmd

      - name: Run!
        run: |
          if [ "${{ matrix.container }}" == "alpine" ]; then
            apk add libstdc++
          fi
          sh gg.cmd node -e 'console.log(1)'
          echo "Nice, let's try again"
          sh gg.cmd node -e 'console.log(1)'
          sh gg.cmd node -v
          sh gg.cmd npm -v
          sh gg.cmd npx -v
          sh gg.cmd java -version
          sh gg.cmd java -version


  E-test-arch:
    if: github.ref == 'refs/heads/main'
    needs: D-stage1
    strategy:
      matrix:
        include:
          - arch: armv7
            target: armv7-unknown-linux-musl

    runs-on: ubuntu-20.04
    steps:
      - name: Download gg
        uses: actions/download-artifact@v2
        with:
          name: gg.cmd

      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu18.04
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            -v "$PWD:/ok"
          run: |
            uname -a
            cd /ok
            sh gg.cmd node -e 'console.log(1)'
            echo "Nice, let's try again"
            sh gg.cmd node -e 'console.log(1)'
            sh gg.cmd node -v
            sh gg.cmd npm -v
            sh gg.cmd npx -v
            sh gg.cmd java -version
            sh gg.cmd java -version


  F-release:
    name: Release!
    needs: [ E-test-OS, E-test-batch, E-test-container, E-test-arch ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ github.token }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.buildnumber.outputs.build_number }}
          release_name: Release ${{ steps.buildnumber.outputs.build_number }}
          draft: false
          prerelease: false

      - name: Download gg
        uses: actions/download-artifact@v2
        with:
          name: gg.cmd

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token}}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gg.cmd
          asset_name: gg.cmd
          asset_content_type: text/x-shellscript
