on:
  workflow_dispatch:
  push:

# Plan (tiers):
# A: Build stage2 (for each target)
# B: Hash (create hash for each target)
# C: Build stage1 (for each target)
# D: Build m
# E Test (for each os target)
# F: Create release

name: gg.cmd
jobs:

  A-stage2-OS:
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            stage22/target
          key: OS-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: cargo pls
        shell: bash
        run: |
          mkdir -p stage22
          mv stage2/* stage22
          rm -rf stage2
          cd stage22
          
          rustup target add ${{ matrix.target }}
          cargo build --release --target=${{ matrix.target }}
          find . -type f -name stage2.exe -exec cp {} ../stage2 \;
          find . -type f -name stage2 -exec cp {} ../stage2 \;


      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: stage2_${{ matrix.target }}
          path: stage2


  A-stage2-container:
    strategy:
      matrix:
        include:
          - container: alpine
            target: x86_64-unknown-linux-musl

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            stage22/target
          key: container-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: cargo pls
        run: |
          mkdir -p stage22
          mv stage2/* stage22
          rm -rf stage2
          cd stage22
          if [ "${{ matrix.container }}" == "alpine" ]
          then
            apk add build-base 
            apk add rustup
            rustup-init -y
            source $HOME/.cargo/env
          fi

          cargo build --release --target=${{ matrix.target }}
          #--target=${{ matrix.target}}
          find . -type f -name stage2.exe -exec cp {} ../stage2 \;
          find . -type f -name stage2 -exec cp {} ../stage2 \;


      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: stage2_${{ matrix.target }}
          path: stage2


  A-stage2-arch:
    strategy:
      matrix:
        include:
          - arch: armv7
            target: armv7-unknown-linux-gnu
          - arch: armv7
            target: armv7-unknown-linux-musl

    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.1.0

      - uses: actions/cache@v2
        with:
          path: cachus
          key: arch-cargo-x7-${{ hashFiles('**/Cargo.lock') }}

      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu18.04
          githubToken: ${{ github.token }}
          setup: mkdir -p "$PWD/artifacts"
          dockerRunArgs: |
            -v "$PWD/artifacts:/artifacts"
            -v "$PWD/cachus:/cachus"

          install: |
            apt-get -y update
            apt-get -y install cargo

          run: |
            cd stage2
            cp -rp /cachus/* . || :
            CARGO_HOME=ok cargo build --release
            cp -rp target /cachus/
            cp -rp ok /cachus/
            cp target/release/stage2 /artifacts/

      - run: |
          sudo chown -R $(id -u):$(id -g) $PWD/artifacts
          sudo chown -R $(id -u):$(id -g) .
          rm -rf stage2
          find $PWD/artifacts -type f -name stage2 -exec cp {} ./stage2 \;

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: stage2_${{ matrix.target }}
          path: stage2


  B-hash:
    needs: [ A-stage2-OS, A-stage2-container, A-stage2-arch ]
    runs-on: ubuntu-20.04
    steps:
      - name: Download stage2 hash
        uses: actions/download-artifact@v2

      - name: Rename to hash
        shell: bash
        run: |
          ls -lah
          du -a
          mkdir hash
          mkdir out
          for dir in stage2_*
          do
            echo dir is $dir
            file=$dir/stage2
            echo file is $file
            hash=$(sha512sum $file | awk '{ print $1 }')
            echo hash is $hash
            cp $file out/$hash
            echo $hash > hash/hash_$dir
          done
          du -a

      - name: Upload hash artifact
        uses: actions/upload-artifact@v2
        with:
          name: hash
          path: hash

      - uses: LanceMcCarthy/Action-AzureBlobUpload@v1.9.0
        with:
          connection_string: ${{ secrets.ConnectionString }}
          container_name: poc
          source_folder: out


  C-stage1-OS:
    needs: B-hash

    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-gnu
          - os: macos-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Download stage2 hash
        uses: actions/download-artifact@v2
        with:
          name: hash
          path: hash

      - name: Hash
        # ENV -> CMAKE -> Code very hard. This very easy
        shell: bash
        run: |
          du -a
          hash=$(cat hash/hash_stage2_${{ matrix.target }})
          echo "now hash is $hash"
          echo "const char *hash = \"$hash\";" > stage1/const.h

      - name: Makus
        shell: bash
        run: |
          cd stage1
          if [ "${{ matrix.target }}" == "x86_64-unknown-linux-musl" ]
          then
            sudo apt install musl-dev musl-tools
            export CC=musl-gcc
          fi
          cmake -B build -DCMAKE_EXE_LINKER_FLAGS='-Os' -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          find . -type f \( -name stage1 -o -name stage1.exe \) -exec cp {} ../stage1_${{ matrix.target }} \;

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: stage1_${{ matrix.target }}
          path: stage1_${{ matrix.target }}


  C-stage1-windows:
    needs: B-hash

    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Download stage2 hash
        uses: actions/download-artifact@v2
        with:
          name: hash
          path: hash

      - name: Hash
        # ENV -> CMAKE -> Code very hard. This very easy
        shell: bash
        run: |
          du -a
          hash=$(cat hash/hash_stage2_${{ matrix.target }})
          echo "now hash is $hash"
          echo "const char *hash = \"$hash\";" > stage1/const.h

      - name: Makus
        shell: cmd
        run: |
          cd stage1
          cmake -B build -DCMAKE_EXE_LINKER_FLAGS='-Os' -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Makus
        shell: bash
        run: |
          find . -type f \( -name stage1 -o -name stage1.exe \) -exec cp {} ../stage1_${{ matrix.target }} \;

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: stage1_${{ matrix.target }}
          path: stage1_${{ matrix.target }}


  C-stage1-container:
    needs: B-hash

    strategy:
      matrix:
        include:
          - container: alpine
            target: x86_64-unknown-linux-musl

    runs-on: ubuntu-20.04
    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v2

      - name: Download stage2 hash
        uses: actions/download-artifact@v2
        with:
          name: hash
          path: hash

      - name: Hash
        # ENV -> CMAKE -> Code very hard. This very easy
        run: |
          du -a
          hash=$(cat hash/hash_stage2_${{ matrix.target }})
          echo "now hash is $hash"
          echo "const char *hash = \"$hash\";" > stage1/const.h

      - name: Makus
        run: |
          cd stage1
          apk add build-base cmake
          cmake -B build -DCMAKE_EXE_LINKER_FLAGS='-Os' -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          find . -type f \( -name stage1 -o -name stage1.exe \) -exec cp {} ../stage1_${{ matrix.target }} \;

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: stage1_${{ matrix.target }}
          path: stage1_${{ matrix.target }}


  C-stage1-arch:
    needs: B-hash

    strategy:
      matrix:
        include:
          - arch: armv7
            target: armv7-unknown-linux-gnu
          - arch: armv7
            target: armv7-unknown-linux-musl

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Download stage2 hash
        uses: actions/download-artifact@v2
        with:
          name: hash
          path: hash

      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu18.04
          githubToken: ${{ github.token }}
          setup: mkdir -p "$PWD/artifacts"
          dockerRunArgs: |
            -v "$PWD/artifacts:/artifacts"
            -v "$PWD:/yes"

          install: |
            apt-get -y update
            apt-get -y install cmake build-essential musl-dev musl-tools

          run: |
            set -x
            cd /yes
            ls -lah
            hash=$(cat hash/hash_stage2_${{ matrix.target }})
            echo "now hash is $hash"
            echo "const char *hash = \"$hash\";" > stage1/const.h
            du -a
            cd stage1
            ls -lah
            if [ "${{ matrix.target }}" == "armv7-unknown-linux-musl" ]
            then
              export CC=musl-gcc
            fi
            mkdir build
            cd build
            cmake .. -DCMAKE_EXE_LINKER_FLAGS='-Os' -DCMAKE_BUILD_TYPE=Release
            make
            find . -type f \( -name stage1 -o -name stage1.exe \) -exec cp {} /artifacts/stage1_${{ matrix.target }} \;

      - run: |
          ls -lah
          ls -lah artifacts
          cp artifacts/* ./

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: stage1_${{ matrix.target }}
          path: stage1_${{ matrix.target }}



  D-stage0:
    needs: [ C-stage1-OS, C-stage1-container, C-stage1-arch, C-stage1-windows ]
    runs-on: ubuntu-latest
    steps:
      - name: Source
        uses: actions/checkout@v2.1.0

      - name: Download stage1 / stage2
        uses: actions/download-artifact@v2

      - name: gg.cmd
        run: |
          sudo apt-get install dos2unix
          du -a
          echo bah
          ls -lah
          mv stage1 _stage1
          mkdir -p .cache/gg
          rm -rf stage1
          for dir in stage1*; do
            for file in "$dir"/*; do
              cp "$file" .cache/gg/
            done
          done
          # Prevent wine from trying to run (if installed on users PC)
          mv .cache/gg/stage1_x86_64-pc-windows-gnu .cache/gg/stage1_zz_x86_64-pc-windows-gnu
          cp _m/init.sh .cache/gg/
          cp _m/init.ps1 .cache/gg/
          chmod +x .cache/gg/init.sh
          tar -zpvcf m.tgz .cache
          unix2dos _m/kick.bat
          cat _m/kick.bat _m/kick.sh m.tgz > gg.cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: gg.cmd
          path: gg.cmd


  E-test-OS:
    needs: D-stage0
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, windows-2019, windows-2022, macOS-11, macOS-12 ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Download m
        uses: actions/download-artifact@v2
        with:
          name: gg.cmd

      - name: Run!
        run: |
          file gg.cmd
          head gg.cmd
          sh gg.cmd node
          echo "Nice, let's try again"
          sh gg.cmd node
  

  E-test-batch:
    needs: D-stage0
    strategy:
      matrix:
        os: [ windows-2019, windows-2022 ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Download m
        uses: actions/download-artifact@v2
        with:
          name: gg.cmd

      - name: Run!
        shell: cmd
        run: |
          .\gg.cmd node
          .\gg.cmd node


  E-test-container:
    needs: D-stage0
    strategy:
      matrix:
        container: [ ubuntu, debian, alpine, archlinux ]

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - name: Download m
        uses: actions/download-artifact@v2
        with:
          name: gg.cmd

      - name: Run!
        run: |
          sh gg.cmd node
          echo "Nice, let's try again"
          sh gg.cmd node


  E-test-arch:
    needs: D-stage0
    strategy:
      matrix:
        include:
          - arch: armv7
            target: armv7-unknown-linux-musl

    runs-on: ubuntu-20.04
    steps:
      - name: Download m
        uses: actions/download-artifact@v2
        with:
          name: gg.cmd

      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu18.04
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            -v "$PWD:/ok"
          run: |
            uname -a
            cd /ok
            ls -lah
            sh gg.cmd node
            echo "Nice, let's try again"
            sh gg.cmd node


  F-release:
    name: Release!
    needs: [ E-test-OS, E-test-batch, E-test-container, E-test-arch ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ github.token }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.buildnumber.outputs.build_number }}
          release_name: Release ${{ steps.buildnumber.outputs.build_number }}
          draft: false
          prerelease: false

      - name: Download m
        uses: actions/download-artifact@v2
        with:
          name: gg.cmd

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token}}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gg.cmd
          asset_name: gg.cmd
          asset_content_type: text/x-shellscript
